"""Real PPPs of the airport: the passengers who arrived at the security checkpoint in
each 5-minute slot, one PPP per day from 16/07/2008 to 31/07/2008.

They are what the student compares his or her scenarios with. They are
generated by a tool of the lecturer from rules that are not published, so
only the PPPs are here (``data/real_ppp.csv``: 288 rows, the start of each
slot, and one column per day).
"""

from __future__ import annotations

from importlib import resources
from pathlib import Path

import pandas as pd


def read_real_ppps(path: str | Path | None = None) -> pd.DataFrame:
    """All the real PPPs: 288 rows (start of the slot), one column per day."""
    if path is None:
        path = Path(str(resources.files("security_filters") / "data" / "real_ppp.csv"))
    return pd.read_csv(path, index_col="slot start", dtype={"slot start": str})


def real_ppp(day: str) -> pd.Series:
    """Real PPP of ``day`` ("YYYY-MM-DD"): passengers in each of the 288 slots."""
    table = read_real_ppps()
    day = str(day)
    if day not in table.columns:
        raise ValueError(f"There is no real PPP for {day}. Days: {table.columns[0]} to "
                         f"{table.columns[-1]}.")
    return table[day].rename("passengers")
